### ISSUE TITLE
Can't access peak explorer

### ISSUE THREAD

**Issue by joewandy** [kmcluskey/FlyMet#43]
Got the following error message

![image](https://user-images.githubusercontent.com/2523391/94422799-880d9d00-017f-11eb-8062-ed862dd6553f.png)

Stack trace:
```
Traceback (most recent call last):
  File "C:\Users\joewa\.virtualenvs\FlyMet-fLQaCvEH\lib\site-packages\django\core\handlers\exception.py", line 34, in inner
    response = get_response(request)
  File "C:\Users\joewa\.virtualenvs\FlyMet-fLQaCvEH\lib\site-packages\django\core\handlers\base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "C:\Users\joewa\.virtualenvs\FlyMet-fLQaCvEH\lib\site-packages\django\core\handlers\base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\joewa\.virtualenvs\FlyMet-fLQaCvEH\lib\site-packages\django\utils\decorators.py", line 130, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "C:\Users\joewa\Work\git\FlyMet\met_explore\views.py", line 471, in peak_explorer
    cache.set('my_group_df', cmpd_selector.get_group_df(peaks), 60*18000)

Exception Type: NameError at /met_explore/peak_explorer/All
Exception Value: name 'cmpd_selector' is not defined
```

**Comment by joewandy** [comment]
False alarm. It works now after pulling the latest code on master.
